import 'package:flutter/material.dart';
/// Light color scheme
/// Every hex value maps 1:1 to the design tokens.
const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF00453D),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF075E54),
  onPrimaryContainer: Color(0xFF8DD5C8),
  inversePrimary: Color(0xFF8CD4C7),
  secondary: Color(0xFF006D2F),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFF5DFD8A),
  onSecondaryContainer: Color(0xFF007232),
  tertiary: Color(0xFF00415B),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFF005A7B),
  onTertiaryContainer: Color(0xFF80D1FF),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF93000A),
  surface: Color(0xFFF7F9FC),
  onSurface: Color(0xFF191C1E),
  onSurfaceVariant: Color(0xFF3F4946),
  surfaceDim: Color(0xFFD8DADD),
  surfaceBright: Color(0xFFF7F9FC),
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerLow: Color(0xFFF2F4F7),
  surfaceContainer: Color(0xFFECEEF1),
  surfaceContainerHigh: Color(0xFFE6E8EB),
  surfaceContainerHighest: Color(0xFFE0E3E6),
  inverseSurface: Color(0xFF2D3133),
  onInverseSurface: Color(0xFFEFF1F4),
  outline: Color(0xFF6F7976),
  outlineVariant: Color(0xFFBEC9C5),
  surfaceTint: Color(0xFF1C695F),
);